pipeline {

    agent any
	
    stages {
        stage ('Checkout SCM') {
            steps {
                checkout scm
            }
        }
        
        stage ('Artifactory Maven Configuration') {
        
            steps {
            
                // tekgsartifactory = Id defined in Artifactory plugin
                //rtServer (
                //    id: "tekgsartifactory",
                //    url: SERVER_URL,
                //    credentialsId: CREDENTIALS
                //)

                rtMavenDeployer (
                    id: "MAVEN_DEPLOYER",
                    serverId: "tekgsartifactory",
                    releaseRepo: "libs-release-local",
                    snapshotRepo: "libs-snapshot-local"
                )

                rtMavenResolver (
                    id: "MAVEN_RESOLVER",
                    serverId: "tekgsartifactory",
                    releaseRepo: "libs-release",
                    snapshotRepo: "libs-snapshot"
                )
            }
        }

        stage ('Build') {
		
		    // ** NOTE: This 'maven3' Maven tool must be configured
            // **       in the global configuration.
		
            steps {
                rtMavenRun (
                    tool: 'maven3',
                    pom: '../pom.xml',
                    goals: 'clean package -B -DskipTests',
                    deployerId: "MAVEN_DEPLOYER",
                    resolverId: "MAVEN_RESOLVER"
                )
            }
        }
        
        stage ('Test') {
        
            steps {
                rtMavenRun (
                    tool: 'maven3',
                    pom: '../pom.xml',
                    goals: 'test',
                    deployerId: "MAVEN_DEPLOYER",
                    resolverId: "MAVEN_RESOLVER"
                )
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: "tekgsartifactory"
                )
            }
        }
    }
}
